{
 "title": "Blockchain Servers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "num_nodes_alive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "network_status:num_nodes_alive" }
   ]
  },
  {
   "title": "block_status:number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "block_status:number" }
   ]
  },
  {
   "title": "block_status:elapsed_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "block_status:elapsed_time_ms" }
   ]
  },
  {
   "title": "consensus_status:health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "consensus_status:health" }
   ]
  },
  {
   "title": "block_finalized (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_finalized:metric"
    }
   ]
  },
  {
   "title": "timer_flag_status:num_enabled_flags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "config:timer_flag_status:num_enabled_flags"
    }
   ]
  },
  {
   "title": "block_last_votes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_last_votes:metric"
    }
   ]
  },
  {
   "title": "timer_flag_status:num_flags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "config:timer_flag_status:num_flags"
    }
   ]
  },
  {
   "title": "rewards:cumulative",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "consensus_status:rewards:cumulative"
    }
   ]
  },
  {
   "title": "num_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status:connection_status:num_connections"
    }
   ]
  },
  {
   "title": "propose_p_2_p_message (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:propose_p_2_p_message:metric"
    }
   ]
  },
  {
   "title": "num_outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status:connection_status:num_outbound"
    }
   ]
  },
  {
   "title": "vote_p_2_p_message (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:vote_p_2_p_message:metric"
    }
   ]
  },
  {
   "title": "num_inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status:connection_status:num_inbound"
    }
   ]
  },
  {
   "title": "vote_before_block (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:vote_before_block:metric"
    }
   ]
  },
  {
   "title": "num_peer_connections_in_progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "network_status:connection_status:num_peer_connections_in_progress"
    }
   ]
  },
  {
   "title": "propose_before_block (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:propose_before_block:metric"
    }
   ]
  },
  {
   "title": "num_peer_candidates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "network_status:connection_status:num_peer_candidates"
    }
   ]
  },
  {
   "title": "vote_after_propose (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:vote_after_propose:metric"
    }
   ]
  },
  {
   "title": "peer_reorg_candidates_whitelisted:metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:peer_reorg_candidates_whitelisted:metric"
    }
   ]
  },
  {
   "title": "p_2_p_tag_consensus_length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_tag_consensus_length:metric"
    }
   ]
  },
  {
   "title": "peer_reorg_candidates_not_whitelisted:metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:peer_reorg_candidates_not_whitelisted:metric"
    }
   ]
  },
  {
   "title": "p_2_p_tag_consensus_max_occur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_tag_consensus_max_occur:metric"
    }
   ]
  },
  {
   "title": "peer_reorg_candidates_redirected:metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:peer_reorg_candidates_redirected:metric"
    }
   ]
  },
  {
   "title": "p_2_p_tag_tx_length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_tag_tx_length:metric"
    }
   ]
  },
  {
   "title": "peer_reorg_below_min_outbound:metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:peer_reorg_below_min_outbound:metric"
    }
   ]
  },
  {
   "title": "p_2_p_tag_tx_max_occur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_tag_tx_max_occur:metric"
    }
   ]
  },
  {
   "title": "connection_status:state_numeric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status:connection_status:state_numeric"
    }
   ]
  },
  {
   "title": "block_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_size:metric"
    }
   ]
  },
  {
   "title": "consensus_status:state_numeric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "consensus_status:state_numeric" }
   ]
  },
  {
   "title": "block_txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_txs:metric"
    }
   ]
  },
  {
   "title": "node_status:health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_status:health" }
   ]
  },
  {
   "title": "block_gas_amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_gas_amount:metric"
    }
   ]
  },
  {
   "title": "node_status:state_numeric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_status:state_numeric" }
   ]
  },
  {
   "title": "block_gas_cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_gas_cost:metric"
    }
   ]
  },
  {
   "title": "event_handler_status:is_enabled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:event_handler_status:is_enabled"
    }
   ]
  },
  {
   "title": "tx_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_bytes:metric"
    }
   ]
  },
  {
   "title": "channel_status:num_event_channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:event_handler_status:channel_status:num_event_channels"
    }
   ]
  },
  {
   "title": "tx_gas_amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_gas_amount:metric"
    }
   ]
  },
  {
   "title": "channel_status:max_channel_life_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:event_handler_status:channel_status:max_channel_life_time_ms"
    }
   ]
  },
  {
   "title": "tx_gas_cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_gas_cost:metric"
    }
   ]
  },
  {
   "title": "channel_status:max_channel_idle_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:event_handler_status:channel_status:max_channel_idle_time_ms"
    }
   ]
  },
  {
   "title": "tx_op_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_op_size:metric"
    }
   ]
  },
  {
   "title": "filter_status:num_event_filters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:event_handler_status:filter_status:num_event_filters"
    }
   ]
  },
  {
   "title": "json_rpc_set:rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_set:rate"
    }
   ]
  },
  {
   "title": "root_state_info:tree_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:db_status:root_state_info:tree_bytes"
    }
   ]
  },
  {
   "title": "json_rpc_set:metric (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_set:metric"
    }
   ]
  },
  {
   "title": "root_state_info:tree_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:db_status:root_state_info:tree_size"
    }
   ]
  },
  {
   "title": "json_rpc_get:rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_get:rate"
    }
   ]
  },
  {
   "title": "num_accounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "targets": [
    {
     "expr": "node_status:db_status:num_accounts"
    }
   ]
  },
  {
   "title": "json_rpc_get:metric (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_get:metric"
    }
   ]
  },
  {
   "title": "num_apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "targets": [
    { "expr": "node_status:db_status:num_apps" }
   ]
  },
  {
   "title": "p_2_p_message_client:rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_client:rate"
    }
   ]
  },
  {
   "title": "state_version_status:num_versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status:state_version_status:num_versions"
    }
   ]
  },
  {
   "title": "p_2_p_message_client:metric (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_client:metric"
    }
   ]
  },
  {
   "title": "tx_pool_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tx_status:tx_pool_size" }
   ]
  },
  {
   "title": "p_2_p_message_server:rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_server:rate"
    }
   ]
  },
  {
   "title": "tx_tracker_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tx_status:tx_tracker_size" }
   ]
  },
  {
   "title": "p_2_p_message_server:metric (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_server:metric"
    }
   ]
  },
  {
   "title": "memory_status:os:usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "memory_status:os:usage_percent" }
   ]
  },
  {
   "title": "client_api_set:rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_set:rate"
    }
   ]
  },
  {
   "title": "used_heap_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memory_status:heap_stats:used_heap_size"
    }
   ]
  },
  {
   "title": "client_api_set:metric (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_set:metric"
    }
   ]
  },
  {
   "title": "malloced_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memory_status:heap_stats:malloced_memory"
    }
   ]
  },
  {
   "title": "client_api_get:rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_get:rate"
    }
   ]
  },
  {
   "title": "disk_status:usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "disk_status:usage_percent" }
   ]
  },
  {
   "title": "client_api_get:metric (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_get:metric"
    }
   ]
  },
  {
   "title": "disk_status:usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "disk_status:usage" }
   ]
  },
  {
   "title": "cpu_status:usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "cpu_status:usage_percent" }
   ]
  }
 ]
}