{
 "title": "Blockchain Servers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "num_nodes_alive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network_status:num_nodes_alive" }
   ]
  },
  {
   "title": "block_status:number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_status:number" }
   ]
  },
  {
   "title": "block_status:elapsed_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_status:elapsed_time_ms" }
   ]
  },
  {
   "title": "node_status:health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_status:health" }
   ]
  },
  {
   "title": "block_last_votes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_last_votes:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:block_last_votes:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:block_last_votes:metric"
    }
   ]
  },
  {
   "title": "node_status:state_numeric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_status:state_numeric" }
   ]
  },
  {
   "title": "propose_p_2_p_message:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:propose_p_2_p_message:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:propose_p_2_p_message:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:propose_p_2_p_message:metric"
    }
   ]
  },
  {
   "title": "consensus_status:health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consensus_status:health" }
   ]
  },
  {
   "title": "vote_p_2_p_message:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:vote_p_2_p_message:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:vote_p_2_p_message:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:vote_p_2_p_message:metric"
    }
   ]
  },
  {
   "title": "consensus_status:state_numeric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consensus_status:state_numeric" }
   ]
  },
  {
   "title": "propose_before_block:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:propose_before_block:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:propose_before_block:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:propose_before_block:metric"
    }
   ]
  },
  {
   "title": "connection_status:num_inbound",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_status:connection_status:num_inbound"
    }
   ]
  },
  {
   "title": "vote_before_block:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:vote_before_block:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:vote_before_block:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:vote_before_block:metric"
    }
   ]
  },
  {
   "title": "connection_status:num_outbound",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_status:connection_status:num_outbound"
    }
   ]
  },
  {
   "title": "vote_after_propose:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:vote_after_propose:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:vote_after_propose:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:vote_after_propose:metric"
    }
   ]
  },
  {
   "title": "state_version_status:num_versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_status:state_version_status:num_versions"
    }
   ]
  },
  {
   "title": "block_txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_txs:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:block_txs:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:block_txs:metric"
    }
   ]
  },
  {
   "title": "tx_pool_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tx_status:tx_pool_size" }
   ]
  },
  {
   "title": "block_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_size:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:block_size:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:block_size:metric"
    }
   ]
  },
  {
   "title": "tx_tracker_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tx_status:tx_tracker_size" }
   ]
  },
  {
   "title": "block_gas_amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_gas_amount:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:block_gas_amount:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:block_gas_amount:metric"
    }
   ]
  },
  {
   "title": "cpu_status:usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_status:usage_percent" }
   ]
  },
  {
   "title": "block_gas_cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:block_gas_cost:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:block_gas_cost:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:block_gas_cost:metric"
    }
   ]
  },
  {
   "title": "memory_status:os:usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_status:os:usage_percent" }
   ]
  },
  {
   "title": "tx_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_bytes:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:tx_bytes:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:tx_bytes:metric"
    }
   ]
  },
  {
   "title": "used_heap_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memory_status:heap_stats:used_heap_size"
    }
   ]
  },
  {
   "title": "tx_op_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_op_size:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:tx_op_size:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:tx_op_size:metric"
    }
   ]
  },
  {
   "title": "malloced_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memory_status:heap_stats:malloced_memory"
    }
   ]
  },
  {
   "title": "tx_gas_amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_gas_amount:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:tx_gas_amount:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:tx_gas_amount:metric"
    }
   ]
  },
  {
   "title": "disk_status:usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "disk_status:usage_percent" }
   ]
  },
  {
   "title": "tx_gas_cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:tx_gas_cost:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:tx_gas_cost:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:tx_gas_cost:metric"
    }
   ]
  },
  {
   "title": "disk_status:usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "disk_status:usage" }
   ]
  },
  {
   "title": "json_rpc_get:rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_get:rate"
    },
    {
     "expr": "client_status:traffic_stats:5_m:json_rpc_get:rate"
    },
    {
     "expr": "client_status:traffic_stats:1_h:json_rpc_get:rate"
    }
   ]
  },
  {
   "title": "state_info:tree_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_status:db_status:state_info:tree_size"
    }
   ]
  },
  {
   "title": "json_rpc_get:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_get:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:json_rpc_get:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:json_rpc_get:metric"
    }
   ]
  },
  {
   "title": "state_info:tree_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_status:db_status:state_info:tree_bytes"
    }
   ]
  },
  {
   "title": "json_rpc_set:rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_set:rate"
    },
    {
     "expr": "client_status:traffic_stats:5_m:json_rpc_set:rate"
    },
    {
     "expr": "client_status:traffic_stats:1_h:json_rpc_set:rate"
    }
   ]
  },
  {
   "title": "json_rpc_set:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:json_rpc_set:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:json_rpc_set:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:json_rpc_set:metric"
    }
   ]
  },
  {
   "title": "p_2_p_message_server:rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_server:rate"
    },
    {
     "expr": "client_status:traffic_stats:5_m:p_2_p_message_server:rate"
    },
    {
     "expr": "client_status:traffic_stats:1_h:p_2_p_message_server:rate"
    }
   ]
  },
  {
   "title": "p_2_p_message_server:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_server:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:p_2_p_message_server:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:p_2_p_message_server:metric"
    }
   ]
  },
  {
   "title": "p_2_p_message_client:rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_client:rate"
    },
    {
     "expr": "client_status:traffic_stats:5_m:p_2_p_message_client:rate"
    },
    {
     "expr": "client_status:traffic_stats:1_h:p_2_p_message_client:rate"
    }
   ]
  },
  {
   "title": "p_2_p_message_client:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:p_2_p_message_client:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:p_2_p_message_client:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:p_2_p_message_client:metric"
    }
   ]
  },
  {
   "title": "client_api_get:rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_get:rate"
    },
    {
     "expr": "client_status:traffic_stats:5_m:client_api_get:rate"
    },
    {
     "expr": "client_status:traffic_stats:1_h:client_api_get:rate"
    }
   ]
  },
  {
   "title": "client_api_get:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_get:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:client_api_get:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:client_api_get:metric"
    }
   ]
  },
  {
   "title": "client_api_set:rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_set:rate"
    },
    {
     "expr": "client_status:traffic_stats:5_m:client_api_set:rate"
    },
    {
     "expr": "client_status:traffic_stats:1_h:client_api_set:rate"
    }
   ]
  },
  {
   "title": "client_api_set:metric (latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_status:traffic_stats:1_m:client_api_set:metric"
    },
    {
     "expr": "client_status:traffic_stats:5_m:client_api_set:metric"
    },
    {
     "expr": "client_status:traffic_stats:1_h:client_api_set:metric"
    }
   ]
  }
 ]
}