# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'tracker'

    static_configs:
    - targets: ['35.221.150.73:8080']

  - job_name: 'node0'

    static_configs:
    - targets: ['35.194.139.219:8080']

  - job_name: 'node1'

    static_configs:
    - targets: ['35.197.60.255:8080']

  - job_name: 'node2'

    static_configs:
    - targets: ['35.247.190.24:8080']

  - job_name: 'node3'

    static_configs:
    - targets: ['35.222.212.217:8080']

  - job_name: 'node4'

    static_configs:
    - targets: ['35.204.62.84:8080']
