const ConsensusConsts = {
  MAJORITY: 2 / 3,
  DAY_MS: 86400000,
  MAX_CONSENSUS_STATE_DB: 1000,
  HEALTH_THRESHOLD_EPOCH: 600,
  STAKE_LOCKUP_EXTENSION: 2592000000, // 30 days as ms
};

const ConsensusMessageTypes = {
  PROPOSE: 'propose',
  VOTE: 'vote',
};

const ConsensusStates = {
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
};

const ValidatorOffenseTypes = {
  INVALID_PROPOSAL: 'INVALID_PROPOSAL',
}

const ConsensusErrorCode = {
  PARSING_PROPOSAL_BLOCK_FAILURE: 1,
  ADDING_TO_BLOCK_POOL_FAILURE: 2,
  NOT_EXTENDING_LNC_ERROR: 3,
  TEMP_DB_CREATION_FAILURE: 4,
  RECEIVED_PROPOSAL: 100,
  OUTDATED_BLOCK: 101,
  PROPOSER_MISMATCH: 102,
  BLOCK_HASH_MISMATCH: 103,
  INVALID_VALIDATORS_SIZE: 104,
  ILL_FORMED_BLOCK: 105,
  INVALID_PREV_BLOCK: 200,
  INVALID_EPOCH: 300,
  MISSING_PROPOSAL_IN_LAST_VOTES: 301,
  MISSING_PROPOSAL_IN_BLOCK_POOL: 302,
  MISSING_DB_FOR_PREV_BLOCK: 303,
  EXECUTING_LAST_VOTES_FAILURE: 304,
  INVALID_LAST_VOTES_STAKES: 305,
  INVALID_PROPOSER: 400,
  OFFENSES_EVIDENCE_MISMATCH: 500,
  INVALID_OFFENSE_TYPE: 501,
  INVALID_EVIDENCE_VOTES_STAKES: 502,
  EXECUTING_EVIDENCE_VOTES_FAILURE: 503,
  INVALID_OFFENSE_COUNTS: 504,
  EXECUTING_TX_FAILURE: 600,
  INVALID_GAS_AMOUNT_TOTAL: 601,
  INVALID_GAS_COST_TOTAL: 602,
  ILL_FORMED_PROPOSAL_TX: 700,
  EXECUTING_PROPOSAL_FAILURE: 701,
  INVALID_STATE_PROOF_HASH: 800,
}

const ConsensusErrorCodesToVoteAgainst = new Set([
  ConsensusErrorCode.ADDING_TO_BLOCK_POOL_FAILURE,
  ConsensusErrorCode.MISSING_DB_FOR_PREV_BLOCK,
  ConsensusErrorCode.INVALID_EPOCH,
  ConsensusErrorCode.MISSING_PROPOSAL_IN_LAST_VOTES,
  ConsensusErrorCode.EXECUTING_LAST_VOTES_FAILURE,
  ConsensusErrorCode.INVALID_LAST_VOTES_STAKES,
  ConsensusErrorCode.INVALID_PROPOSER,
  ConsensusErrorCode.BLOCK_HASH_MISMATCH,
  ConsensusErrorCode.INVALID_VALIDATORS_SIZE,
  ConsensusErrorCode.ILL_FORMED_BLOCK,
  ConsensusErrorCode.INVALID_PREV_BLOCK,
  ConsensusErrorCode.INVALID_PROPOSER,
  ConsensusErrorCode.OFFENSES_EVIDENCE_MISMATCH,
  ConsensusErrorCode.INVALID_OFFENSE_TYPE,
  ConsensusErrorCode.INVALID_EVIDENCE_VOTES_STAKES,
  ConsensusErrorCode.EXECUTING_EVIDENCE_VOTES_FAILURE,
  ConsensusErrorCode.INVALID_OFFENSE_COUNTS,
  ConsensusErrorCode.EXECUTING_TX_FAILURE,
  ConsensusErrorCode.INVALID_GAS_AMOUNT_TOTAL,
  ConsensusErrorCode.INVALID_GAS_COST_TOTAL,
  ConsensusErrorCode.ILL_FORMED_PROPOSAL_TX,
  ConsensusErrorCode.EXECUTING_PROPOSAL_FAILURE,
  ConsensusErrorCode.INVALID_STATE_PROOF_HASH,
]);

module.exports = {
  ConsensusMessageTypes,
  ConsensusConsts,
  ConsensusStates,
  ValidatorOffenseTypes,
  ConsensusErrorCode,
  ConsensusErrorCodesToVoteAgainst,
}
