const ConsensusConsts = {
  MAJORITY: 2 / 3,
  DAY_MS: 86400000,
  MAX_CONSENSUS_LOGS_IN_STATES: 1000,
  MAX_FINALIZED_BLOCK_INFO_ON_MEM: 10000,
  HEALTH_THRESHOLD_EPOCH: 600,
  STAKE_LOCKUP_EXTENSION: 2592000000, // 30 days as ms
};

const ConsensusMessageTypes = {
  PROPOSE: 'propose',
  VOTE: 'vote',
};

const ConsensusStates = {
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
};

const ValidatorOffenseTypes = {
  INVALID_PROPOSAL: 'INVALID_PROPOSAL',
}

const ConsensusErrorCode = {
  PARSING_PROPOSAL_BLOCK_FAILURE: 1,
  NOT_EXTENDING_LNC_ERROR: 2,
  TEMP_DB_CREATION_FAILURE: 3,
  INVALID_CONSENSUS_TX: 100,
  PROPOSER_MISMATCH: 103,
  BLOCK_HASH_MISMATCH: 104,
  MISSING_PREV_BLOCK: 200,
  MISSING_DB_FOR_PREV_BLOCK: 201,
  ILL_FORMED_BLOCK: 300,
  INVALID_GENESIS_BLOCK: 301,
  INVALID_CHAIN: 302,
  INVALID_EPOCH: 303,
  INVALID_VALIDATORS_SIZE: 304,
  INVALID_PROPOSER: 305,
  EXECUTING_LAST_VOTES_FAILURE: 306,
  INVALID_LAST_VOTES_STAKES: 307,
  MISSING_PROPOSAL_IN_LAST_VOTES: 308,
  OFFENSES_EVIDENCE_MISMATCH: 309,
  INVALID_OFFENSE_TYPE: 310,
  INVALID_EVIDENCE_VOTES_STAKES: 311,
  EXECUTING_EVIDENCE_VOTES_FAILURE: 312,
  INVALID_OFFENSE_COUNTS: 313,
  EXECUTING_TX_FAILURE: 314,
  INVALID_RECEIPTS: 315,
  INVALID_GAS_AMOUNT_TOTAL: 316,
  INVALID_GAS_COST_TOTAL: 317,
  INVALID_STATE_PROOF_HASH: 318,
  ILL_FORMED_PROPOSAL_TX: 319,
  EXECUTING_PROPOSAL_FAILURE: 320,
  ADDING_TO_BLOCK_POOL_FAILURE: 400,
}

const ConsensusErrorCodesToVoteAgainst = new Set([
  ConsensusErrorCode.ADDING_TO_BLOCK_POOL_FAILURE,
  ConsensusErrorCode.INVALID_EPOCH,
  ConsensusErrorCode.MISSING_PROPOSAL_IN_LAST_VOTES,
  ConsensusErrorCode.EXECUTING_LAST_VOTES_FAILURE,
  ConsensusErrorCode.INVALID_LAST_VOTES_STAKES,
  ConsensusErrorCode.INVALID_PROPOSER,
  ConsensusErrorCode.BLOCK_HASH_MISMATCH,
  ConsensusErrorCode.INVALID_VALIDATORS_SIZE,
  ConsensusErrorCode.ILL_FORMED_BLOCK,
  ConsensusErrorCode.OFFENSES_EVIDENCE_MISMATCH,
  ConsensusErrorCode.INVALID_OFFENSE_TYPE,
  ConsensusErrorCode.INVALID_EVIDENCE_VOTES_STAKES,
  ConsensusErrorCode.EXECUTING_EVIDENCE_VOTES_FAILURE,
  ConsensusErrorCode.INVALID_OFFENSE_COUNTS,
  ConsensusErrorCode.EXECUTING_TX_FAILURE,
  ConsensusErrorCode.INVALID_RECEIPTS,
  ConsensusErrorCode.INVALID_GAS_AMOUNT_TOTAL,
  ConsensusErrorCode.INVALID_GAS_COST_TOTAL,
  ConsensusErrorCode.INVALID_CONSENSUS_TX,
  ConsensusErrorCode.ILL_FORMED_PROPOSAL_TX,
  ConsensusErrorCode.EXECUTING_PROPOSAL_FAILURE,
  ConsensusErrorCode.INVALID_STATE_PROOF_HASH,
]);

module.exports = {
  ConsensusMessageTypes,
  ConsensusConsts,
  ConsensusStates,
  ValidatorOffenseTypes,
  ConsensusErrorCode,
  ConsensusErrorCodesToVoteAgainst,
}
