name: AIN-blockchain CI/CD

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
env:
  PERF_TEST_PIPELINE_PROJECT_ID: ${{ secrets.PERF_TEST_PIPELINE_GCP_PROJECT_ID }}
  PERF_TEST_PIPELINE_GCE_INSTANCE: ${{ secrets.PERF_TEST_PIPELINE_GCE_INSTANCE }}
  PERF_TEST_PIPELINE_GCE_INSTANCE_ZONE: ${{ secrets.PERF_TEST_PIPELINE_GCE_INSTANCE_ZONE }}
jobs:
  performance_test:
    runs-on: ubuntu-latest
    steps:
      - name: GCP Github Action
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.PERF_TEST_PIPELINE_GCP_SA_KEY }}
          project_id: ${{ secrets.PERF_TEST_PIPELINE_GCP_PROJECT_ID }}
      - name: Connect GCE And execute docker ps
        run: |-
          gcloud compute ssh "$PERF_TEST_PIPELINE_GCE_INSTANCE" --zone "$PERF_TEST_PIPELINE_GCE_INSTANCE_ZONE" -- 'cd ~/../workspace/ain-benchmark && nohup sh start_test.sh >> test_log.txt'
      - name: test
        run: echo "${{ github.event.pull_request.head.ref }}"
