name: AIN-blockchain CI/CD

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
jobs:
  build_and_test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup node environment for testing
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: yarn install
        run: yarn install
      # - name: run unittest
      #   run: yarn run test_unit
      - name: run integration test
        if: github.event.pull_request.base.ref == 'master'   # integration test only run when master merging
        run: yarn run test_dapp
  check_protocol_version:
    if: ${{ github.event_name == 'push' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        if: github.event_name == 'push'
        run: echo ${{github.event_name}}
      - name: get current version
        run: echo "VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: get min/max versions
        run: |
          echo "MIN_VERSION=$(cat client/protocol_versions.json | jq -r --arg var "$VERSION" '.[$var].min')" >> $GITHUB_ENV
          echo "MAX_VERSION=$(cat client/protocol_versions.json | jq -r --arg var "$VERSION" '.[$var].max')" >> $GITHUB_ENV
      - name: send results
        env:
          SLACK_WEBHOOK_TOKEN: ${{ secrets.SLACK_WEBHOOK_TOKEN }}
        run: |
          curl -X POST https://hooks.slack.com/services/$SLACK_WEBHOOK_TOKEN \
            -H "Content-Type: application/json" \
            -d '{"username": "ain-blockchain",
            "channel": "blockchain-testnet-deploy",
            "text": "New PR has just been merged(${{ github.ref }}, ${{ github.sha }}).\nCurrent version: '"$VERSION"', compatible with min('"$MIN_VERSION"'), max('"$MAX_VERSION"')",
            "icon_emoji": ":gem:"}'
