name: AIN-blockchain CI/CD

on:
  # pull_request:
  #   types: [opened]
  #   branch: [develop]
  push:
    branches:
      - 'feature/cicd/updates'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup node environment for testing
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: npm install
        run: npm install
      - name: run unittest
        run: npm run test_unit
      # - name: run integration test
      #   run: npm run test_integration
